# Generated by Django 4.2.6 on 2023-10-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('last_deal', models.FloatField()),
                ('opening_prices', models.FloatField()),
                ('max', models.FloatField()),
                ('min', models.FloatField()),
                ('category', models.CharField(choices=[('fr', 'foreign'), ('ru', 'russian')], max_length=10)),
            ],
        ),
    ]
