# Generated by Django 4.2.6 on 2023-10-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('coin_type', models.CharField(max_length=50)),
                ('tx_fee', models.FloatField()),
                ('img', models.CharField(max_length=300)),
                ('price', models.FloatField()),
            ],
        ),
    ]
